"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( $conflicted$untracked$modified$staged$renamed$deleted)](white) ($ahead_behind)]($style)"
style = "white"
conflicted = "\uf408"
untracked = "\uf408"
modified = "\uf408"
staged = "\uf408"
renamed = "\uf408"
deleted = "\uf408"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
