unbind r
bind r source-file ~/.tmux.conf

is_vim="tmux display -p '#{pane_current_command}' \
    | grep -iqE '(vim|view|vi|vimi|vimdiff|git)'"

set-option -g update-environment "DISPLAY"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-bg "#0087d7"
set -g @minimal-tmux-fg "#000000"

set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# vim-tmux-navigator
bind-key -n "C-left"  if-shell "$is_vim" "send-keys C-left"  "select-pane -L"
bind-key -n "C-down"  if-shell "$is_vim" "send-keys C-down"  "select-pane -D"
bind-key -n "C-up"    if-shell "$is_vim" "send-keys C-up"  "select-pane -U"
bind-key -n "C-right" if-shell "$is_vim" "send-keys C-right"  "select-pane -R"
# bind-key -n C-\ if-shell "$is_vim" "send-keys C-\"  "select-pane -l"
bind-key -T copy-mode-vi "C-left"  select-pane -L
bind-key -T copy-mode-vi "C-down"  select-pane -D
bind-key -T copy-mode-vi "C-up"    select-pane -U
bind-key -T copy-mode-vi "C-right" select-pane -R

# vim-tmux-resizer
bind-key -n "S-left"  if-shell "$is_vim" "send-keys S-left"  "resize-pane -L 10"
bind-key -n "S-down"  if-shell "$is_vim" "send-keys S-down"  "resize-pane -D 5"
bind-key -n "S-up"    if-shell "$is_vim" "send-keys S-up"  "resize-pane -U 5"
bind-key -n "S-right" if-shell "$is_vim" "send-keys S-right"  "resize-pane -R 10"
bind-key -T copy-mode-vi "S-left"  resize-pane -L 10
bind-key -T copy-mode-vi "S-down"  resize-pane -D 10
bind-key -T copy-mode-vi "S-up"    resize-pane -U 5
bind-key -T copy-mode-vi "S-right" resize-pane -R 5

set-option -g xterm-keys on
set-option -g focus-events on

set -g mouse on
set -g default-terminal "xterm-256color"
set-window-option -g mode-keys vi
run '~/.tmux/plugins/tpm/tpm'
